apiVersion: standard.oam.dev/v1alpha1
kind: Autoscaler
metadata:
  name: example-scaler
spec:
  minReplicas: 4                      # optional, Defaults: 1
  maxReplicas: 8                      # optional, cannot be less that minReplicas
  triggers:
    - name: resource-example          # optional. 如果为空，自动生成，需要 mutation/validation
      enabled: true                   # optional. whether to take effect. default is true
      type: cpu                       # required. cpu/memory/storage/ephemeral-storage、cron、pps、qps/rps、custom
      condition:
        target: 85                    # required. 阈值，扩容临界值  resource --> 85%
  targetWorkload:                     # set by users or be auto-patched by outsiders, like OAM
    name: "php-apache"
    apiVersion: "extensions/v1beta1"  # optional
    kind: "Deployment"                # optional
